### PR TITLE
Fix HTML crawling

### LINKED ISSUE #19: Error: ENOENT: no such file or directory, stat 'build/public'
Hi there,

I can run this plug-in locally successfully. However, when I deploy the site on Netlify. I'm getting this error message(see screenshot). Can you please advise a solution to this error?
Screen Shot 2020-05-04 at 2 08 49 PM

### PR DESCRIPTION
**Pull request by ehmicky**
Fixes #19.

HTML crawling fails when one of the paths passed as `checkPaths` does not exist.

This PR also makes the crawling happen in parallel for all `checkPaths` (instead of serially) and replace custom crawling by the `readdirp` library.

### CODE REVIEW

**Review by swyxio — APPROVED** [review]
lgtm. should we warn if the path doesnt exist at all? likely to be a user error.

**Comment by ehmicky** [comment]
You're right: fixed in cbb9597826be3167bef6bd93179d02f4f5584eed.

File: plugin/pluginCore.js [hunk 1]
```diff
@@ -29,37 +28,32 @@ exports.runPa11y = async function({ htmlFilePaths, testMode, debugMode }) {
...
-  return filelist;
-};
+const findHtmlFiles = async function(fileAndDirPath, build) {
+  if (await isDirectory(fileAndDirPath)) {
+    const fileInfos = await readdirp.promise(fileAndDirPath, { fileFilter: '*.html' })
+    return fileInfos.map(({ fullPath }) => fullPath)
+  }
+
+  if (!(await isFile(fileAndDirPath))) {
+    build.failBuild(`Input "checkPaths" does not exist: ${fileAndDirPath}`)
```
Comment (swyxio) [inline plugin/pluginCore.js]: wait.. why fail build? should we just warn instead?

also i think the wording can be better.. maybe `Warning: Folder ${fileAndDirPath} was provided in "checkPaths", but does not exist - it either indicates something went wrong with your build, or you can simply delete this folder from your "checkPaths" in netlify.toml`

Comment (ehmicky) [reply plugin/pluginCore.js]: Fixed!

**Comment by swyxio** [comment]
v 0.0.9
